训练误差： 模型在训练数据上的误差
泛化误差：新数据上的误差


过拟合：泛化能力不行
欠拟合：验证集和测试集都很差，模型过于简单
![fit](../img/fit.png)

模型容量需要匹配数据复杂度

In [1]:
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
max_degree = 20  # 多项式的最大阶数
n_train, n_test = 100, 100  # 训练和测试数据集大小
true_w = np.zeros(max_degree)  # 分配大量的空间
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

features = np.random.normal(size=(n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i + 1)  # gamma(n)=(n-1)!
# labels的维度:(n_train+n_test,)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=0.1, size=labels.shape)

In [4]:
# NumPy ndarray转换为tensor
true_w, features, poly_features, labels = [torch.tensor(x, dtype=
    torch.float32) for x in [true_w, features, poly_features, labels]]

features[:2], poly_features[:2, :], labels[:2]

(tensor([[-0.1478],
         [-1.0631]]),
 tensor([[ 1.0000e+00, -1.4778e-01,  1.0920e-02, -5.3794e-04,  1.9875e-05,
          -5.8744e-07,  1.4469e-08, -3.0547e-10,  5.6430e-12, -9.2661e-14,
           1.3694e-15, -1.8398e-17,  2.2657e-19, -2.5757e-21,  2.7189e-23,
          -2.6788e-25,  2.4743e-27, -2.1509e-29,  1.7660e-31, -1.3736e-33],
         [ 1.0000e+00, -1.0631e+00,  5.6510e-01, -2.0025e-01,  5.3223e-02,
          -1.1316e-02,  2.0051e-03, -3.0452e-04,  4.0467e-05, -4.7801e-06,
           5.0817e-07, -4.9113e-08,  4.3510e-09, -3.5582e-10,  2.7019e-11,
          -1.9150e-12,  1.2724e-13, -7.9570e-15,  4.6995e-16, -2.6295e-17]]),
 tensor([4.5717, 0.6426]))